name: Request firmware signature
description: Request the signature of a Gluon firmware manifest.
labels: [signing-request]
title: "[Signature Request] {version} ({channel})"
body:
  - type: markdown
    attributes:
      value: |
        Request the signature of a Gluon firmware manifest.
        Enter version and channel below. The repository owner will have to approve this request.
  - type: input
    id: version
    attributes:
      label: Version
      description: "Enter the firmware version (letters, numbers, dot, underscore, dash only)."
      placeholder: "e.g. v2024.1.2"
    validations:
      required: true
  - type: dropdown
    id: channel
    attributes:
      label: Release channel
      description: "Select the release channel."
      options:
        - stable
        - testing
        - experimental
    validations:
      required: true
