name: "Sign Firmware Manifest"

on:
  issue_comment:
    types: [created]

jobs:
  sign-manifest:
    if: |
      github.event.issue.state == 'open' &&
      contains(github.event.comment.body, 'Approve signature') &&
      github.event.comment.author_association == 'OWNER'
    runs-on: ubuntu-latest
    env:
      ECDSAUTILS_VERSION: v0.4.2

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: React with thumbs up
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              comment_id: context.payload.comment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: '+1'
            })
      - name: Parse issue form
        id: form
        uses: issue-ops/parser@v4
        with:
          issue-form-template: firmware-signing.yml
          body: ${{ github.event.issue.body }}
      - name: Validate issue data
        id: validate
        uses: actions/github-script@v7
        with:
          script: |
            const version = process.env.VERSION;
            const channel = process.env.CHANNEL[0];
            if (!version || !channel) {
              core.setFailed('Version or channel not found or invalid.');
              return;
            }
            if (!["stable", "testing", "experimental"].includes(channel)) {
              core.setFailed('Invalid channel: ' + channel);
              return;
            }
            core.setOutput('version', version);
            core.setOutput('channel', channel);
        env:
          VERSION: ${{ steps.form.outputs.version }}
          CHANNEL: ${{ steps.form.outputs.channel }}
      - name: Download manifest
        run: |
          curl -fsSL "$FIRMWARE_BASE_URL/${{ steps.validate.outputs.version }}/${{ steps.validate.outputs.channel }}/sysupgrade/${{ steps.validate.outputs.channel }}.manifest" -o manifest
        env:
          FIRMWARE_BASE_URL: ${{ vars.FIRMWARE_BASE_URL }}
      - name: Install ecdsautils
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool
          curl -fsSL -o ecdsautils.tar.gz https://github.com/freifunk-gluon/ecdsautils/archive/refs/tags/${ECDSAUTILS_VERSION}.tar.gz
          tar -xzf ecdsautils.tar.gz
          cd ecdsautils-${ECDSAUTILS_VERSION#v} && make && sudo make install
      - name: Sign manifest and extract signature
        id: sign
        run: |
          # Pass name of env var containing the private key
          signature=$(./sign.sh PRIVATE_KEY manifest)
          echo "$signature" >> $GITHUB_OUTPUT
          cat manifest
        env:
          PRIVATE_KEY: ${{ secrets.FIRMWARE_SIGNING_KEY }}
      - name: Post signature as comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Signature for ${{ steps.validate.outputs.version }} [${{ steps.validate.outputs.channel }}.manifest]($FIRMWARE_BASE_URL/${{ steps.validate.outputs.version }}/${{ steps.validate.outputs.channel }}/sysupgrade/${{ steps.validate.outputs.channel }}.manifest):

              \`\`\`
              ${{ steps.sign.outputs.signature }}
              \`\`\``
            })
      - name: Close issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            })
